# Generated by Django 5.1.2 on 2025-10-30 02:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(default=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='phonenumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Transer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_account', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2025, 10, 30, 2, 17, 20, 842556, tzinfo=datetime.timezone.utc))),
                ('narration', models.CharField(default=False, max_length=2000)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
