# Generated by Django 5.1.2 on 2025-11-03 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_bankdetails_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transer',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 11, 3, 22, 26, 25, 849039, tzinfo=datetime.timezone.utc)),
        ),
    ]
