# Generated by Django 5.1.2 on 2025-11-03 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_transer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transer',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 11, 3, 22, 56, 33, 154231, tzinfo=datetime.timezone.utc)),
        ),
    ]
