# Generated by Django 5.1.2 on 2025-11-04 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_alter_transer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transer',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 11, 4, 20, 46, 42, 308508, tzinfo=datetime.timezone.utc)),
        ),
    ]
