# Generated by Django 5.1.2 on 2025-11-09 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_transer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transer',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 11, 9, 16, 48, 56, 668415, tzinfo=datetime.timezone.utc)),
        ),
    ]
