# Generated by Django 5.1.2 on 2026-05-21 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_alter_transer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transer',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 21, 18, 4, 0, 157092, tzinfo=datetime.timezone.utc)),
        ),
    ]
