# Generated by Django 5.1.2 on 2025-10-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_customuser_is_verified_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
